### PR TITLE
first commit of isma page#8

### PR DESCRIPTION
**Pull request by isma444**
#8  isma crée

### CODE REVIEW

**Review by seb-lecampus — CHANGES_REQUESTED** [review]
There is a empty line !! 11 !

**Review by seb-lecampus — APPROVED** [review]
perfect !

**Review by baptiste-mrtn — APPROVED** [review]
jgshjedvv<sgfgVZBVCSQJG4GCQN J5NBJB VFDENYT6

**Review by IreneuszPISKORSKI — APPROVED** [review]
ok!

**Review by SJSzyn — APPROVED** [review]
Looks good

**Pull request merged**
